### PR TITLE
Add Typings

### PR DESCRIPTION
**Pull request by FireController1847**
The second you merge the other PR I made it should not show as big of changes.

- [x] Ready To Merge

### CODE REVIEW

**Comment by FireController1847** [comment]
Also don't forget that when you're ready to publish it to NPM.

**Comment by benkaiser** [comment]
Sorry for the delay on this one, could you update the PR so it's just the typings change? You might just need to rebase on master

**Comment by FireController1847** [comment]
I hate github sometimes, but I made it work *finally*.

**Comment by FireController1847** [comment]
Also, about to PR two more things, one of them being an emergency fix for the options

**Comment by benkaiser** [comment]
Alright 👍

**Pull request merged**
