### PR TITLE
Update Entire Module (The Promise Update)

### PR DESCRIPTION
**Pull request by FireController1847**
I was just thinking it's probably about time for this to be done. This is a breaking change, but it is worth it for the easier way to improve code in the future.

### CODE REVIEW

**Comment by FireController1847** [comment]
Also, if you want help improving this for future use, I'd be willing to make more PR's in the future.

**Comment by benkaiser** [comment]
How about we drop call back support altogether in favor of promises? I'd we're breaking the API I suggest we bump the major version too so we don't break people.

**Comment by FireController1847** [comment]
kk

Edit: To add promise support and keep this playlist request loop you have, the loop itself must keep the promise. This is ultimately the best way to do it. We might as well just keep the callback for those who don't like promises.

Edit 2: I'm currently working on a way to make this work. I'm cleaning up your package.json file as github is erroring that the MIT license is invalid aswell.

**Comment by benkaiser** [comment]
Looking good, let me know when you're ready for me to merge it

**Comment by FireController1847** [comment]
It's good to go now :)

**Comment by benkaiser** [comment]
Module published to NPM, thanks for contributing :+1:

**Comment by FireController1847** [comment]
Anytime! :)

**Pull request merged**
