### PR TITLE
Add Support for Custom MaxResults

### PR DESCRIPTION
**Pull request by FireController1847**
That way we're not spamming the API with huge playlists, allow us to specify maxResults if we need.

- [x] Ready to merge.

### CODE REVIEW

**Comment by FireController1847** [comment]
Don't merge this yet. I will be fixing this later.

**Comment by benkaiser** [comment]
Let me know when fixed.
Some additional advice:

- check if callback is undefined, then set callback to maxResults (this helps us avoid breaking the API).
- bump the minor version in package.json just in case anyone depends on it won't automatically install the newer potentially api-breaking change

**Comment by FireController1847** [comment]
@benkaiser I actually have a question: How many requests can you send to google for this API without them getting mad? I mean, if a playlist has 1000 items, it'd be 200 requests. Do they even care?

**Comment by FireController1847** [comment]
I'm going to close this as I honestly don't think Google cares for stuff like this (ex. my question above).

**Comment by FireController1847** [comment]
Lol when it readded the commits it readded everything. It's literally the same as my pull request an hour ago so it should merge fine. Tested and working 👌

**Comment by benkaiser** [comment]
Can you also rebase this one so it's only the maxresults change?

**Comment by FireController1847** [comment]
Ayy! Only after 15 minutes of screwing everything up I did it! xD

**Comment by benkaiser** [comment]
Will publish to NPM later

**Pull request merged**
